fallback = ''

[matching]
'discord' = 'ﭮ'
'Nextcloud' = ''
'Steam' = ''
'vlc' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
