
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle :compinstall filename '/home/wattenberg/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
# End of lines configured by zsh-newuser-install
#
eval "$(starship init zsh)"

# Loop through all .zsh files in ~/.zsh directory
for file in $XDG_CONFIG_HOME/zsh/*; do
  # Check if it's a regular file and not a directory
  if [[ -f "$file" ]]; then
    source "$file"
  fi
done

path+=("/home/wattenberg/Flutter/flutter/bin")
path+=("/home/wattenberg/.local/bin")
export CHROME_EXECUTABLE="/usr/bin/google-chrome-stable"
# export ANDROID_HOME="/home/Android/Sdk"
export PATH
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
#        . "/opt/miniconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/opt/miniconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<
